import type { Mission } from '@/types/mission'

export const missions: Mission[] = [
  {
    id: 'mars-scout',
    name: 'Reconhecimento de Marte',
    category: 'Exploração',
    difficulty: 'Média',
    status: 'Disponível',
    description: 'Mapeie zonas de interesse e colete dados sobre a superfície marciana.',
    objectives: [
      { title: 'Capturar imagens', description: 'Registro visual de 12 pontos de interesse.' },
      { title: 'Analisar terreno', description: 'Classificar riscos e rotas otimizadas.' },
    ],
    reward: { xp: 300, credits: 1800 },
  },
  {
    id: 'asteroid-analysis',
    name: 'Análise de Asteroide',
    category: 'Pesquisa',
    difficulty: 'Difícil',
    status: 'Disponível',
    description: 'Estude a composição de um asteroide em rota de colisão.',
    objectives: [{ title: 'Coletar amostras', description: 'Recolher amostras com segurança.' }],
    reward: { xp: 460, credits: 2500 },
  },
  {
    id: 'belt-rescue',
    name: 'SOS na Cinturão',
    category: 'Resgate',
    difficulty: 'Épica',
    status: 'Bloqueada',
    description: 'Socorra tripulantes perdidos na região do cinturão de asteroides.',
    objectives: [{ title: 'Localizar tripulantes', description: 'Encontrar sinal de emergência.' }],
    reward: { xp: 680, credits: 3600 },
  },
  {
    id: 'urgent-delivery',
    name: 'Entrega Urgente',
    category: 'Carga',
    difficulty: 'Fácil',
    status: 'Aceita',
    description: 'Entregue suprimentos médicos em uma estação remota.',
    objectives: [{ title: 'Transportar carga', description: 'Entregar sem perdas.' }],
    reward: { xp: 220, credits: 1400 },
  },
  {
    id: 'unknown-signal',
    name: 'Sinal Desconhecido',
    category: 'Anomalia',
    difficulty: 'Difícil',
    status: 'Disponível',
    description: 'Investigue um pulso energético de origem desconhecida.',
    objectives: [{ title: 'Escanear emissão', description: 'Capturar a assinatura do pulso.' }],
    reward: { xp: 540, credits: 3100 },
  },
  {
    id: 'sector-pirates',
    name: 'Piratas no Setor 7',
    category: 'Combate',
    difficulty: 'Épica',
    status: 'Disponível',
    description: 'Repelir uma incursão de corsários próxima à borda do setor.',
    objectives: [{ title: 'Neutralizar ameaça', description: 'Desativar a presença hostil.' }],
    reward: { xp: 720, credits: 4200 },
  },
  {
    id: 'station-collapse',
    name: 'Estação em Colapso',
    category: 'Emergência',
    difficulty: 'Difícil',
    status: 'Disponível',
    description: 'Apoie a evacuação de uma estação em falha estrutural.',
    objectives: [{ title: 'Evacuar pessoal', description: 'Garantir a segurança de todos.' }],
    reward: { xp: 590, credits: 3300 },
  },
  {
    id: 'solar-storm',
    name: 'Tempestade Solar',
    category: 'Fenômeno',
    difficulty: 'Média',
    status: 'Disponível',
    description: 'Estude os efeitos de uma tempestade solar em uma rede de satélites.',
    objectives: [{ title: 'Proteção de satélites', description: 'Reforçar o sistema de comunicação.' }],
    reward: { xp: 380, credits: 2100 },
  },
  {
    id: 'free-map',
    name: 'Cartografar Região',
    category: 'Exploração Livre',
    difficulty: 'Fácil',
    status: 'Disponível',
    description: 'Mapeie uma zona ainda não registrada do espaço.',
    objectives: [{ title: 'Registrar setor', description: 'Completar o mapa de exploração.' }],
    reward: { xp: 260, credits: 1500 },
  },
  {
    id: 'ancient-traces',
    name: 'Vestígios Antigos',
    category: 'História',
    difficulty: 'Épica',
    status: 'Bloqueada',
    description: 'Descubra sinais de uma civilização antiga nas margens do sistema.',
    objectives: [{ title: 'Inspecionar ruínas', description: 'Localizar artefatos antigos.' }],
    reward: { xp: 840, credits: 5000 },
  },
]
