import type { Ship } from '@/types/ship'

export const ships: Ship[] = [
  {
    id: 'aurora-scout',
    name: 'Aurora Scout',
    manufacturer: 'Helios Outpost',
    class: 'explorer',
    rarity: 'common',
    level: 3,
    description: 'Uma nave leve dedicada à exploração inicial de setores remotos.',
    lore: 'Projetada para missões de reconhecimento com autonomia e confiabilidade excepcionais.',
    price: 1800,
    stats: { speed: 72, hyperdrive: 84, storage: 38, fuel: 70, energy: 65, shield: 46 },
    unlocked: true,
    owned: true,
    placeholder_color: '#00FFFF',
  },
  {
    id: 'voidbreaker-x',
    name: 'Voidbreaker X',
    manufacturer: 'Kestrel Dynamics',
    class: 'fighter',
    rarity: 'uncommon',
    level: 5,
    description: 'Caça de alto desempenho para engajamentos curtos e evasivas agressivas.',
    lore: 'Uma obra-prima militar criada para romper formações inimigas com velocidade extrema.',
    price: 3200,
    stats: { speed: 91, hyperdrive: 68, storage: 28, fuel: 62, energy: 78, shield: 58 },
    unlocked: true,
    owned: false,
    placeholder_color: '#FF4444',
  },
  {
    id: 'starwhale-cargo',
    name: 'Starwhale Cargo',
    manufacturer: 'Tethys Logistics',
    class: 'cargo',
    rarity: 'common',
    level: 2,
    description: 'Transportadora versátil para rotas comerciais e abastecimento interplanetário.',
    lore: 'A frota logística da região adotou esta nave por estabilidade e capacidade de carga.',
    price: 2200,
    stats: { speed: 54, hyperdrive: 72, storage: 92, fuel: 74, energy: 61, shield: 49 },
    unlocked: true,
    owned: true,
    placeholder_color: '#FFD700',
  },
  {
    id: 'shadow-phantom',
    name: 'Shadow Phantom',
    manufacturer: 'Nocturne Labs',
    class: 'stealth',
    rarity: 'rare',
    level: 7,
    description: 'Nave furtiva com sensores avançados para infiltrações e reconhecimento sigiloso.',
    lore: 'Um projeto clandestino que combina invisibilidade parcial e energia de alto rendimento.',
    price: 5400,
    stats: { speed: 86, hyperdrive: 81, storage: 34, fuel: 58, energy: 88, shield: 67 },
    unlocked: true,
    owned: false,
    placeholder_color: '#8B00FF',
  },
  {
    id: 'nova-titan',
    name: 'Nova Titan',
    manufacturer: 'Aegis Command',
    class: 'capital',
    rarity: 'epic',
    level: 9,
    description: 'Capital de guerra com blindagem pesada e capacidade estratégica incomparável.',
    lore: 'A presença da Nova Titan é um símbolo de domínio em áreas de fronteira.',
    price: 8700,
    stats: { speed: 61, hyperdrive: 58, storage: 85, fuel: 71, energy: 83, shield: 93 },
    unlocked: false,
    owned: false,
    placeholder_color: '#FF6B00',
  },
  {
    id: 'nebula-drifter',
    name: 'Nebula Drifter',
    manufacturer: 'Lumen Relay',
    class: 'explorer',
    rarity: 'rare',
    level: 6,
    description: 'Nave de exploração longa distância com sistemas de mapeamento de alto alcance.',
    lore: 'Ideal para corredores de fronteira e pesquisas em zonas de alta radiação.',
    price: 4100,
    stats: { speed: 79, hyperdrive: 90, storage: 54, fuel: 68, energy: 74, shield: 63 },
    unlocked: true,
    owned: true,
    placeholder_color: '#00FF88',
  },
  {
    id: 'iron-sentinel',
    name: 'Iron Sentinel',
    manufacturer: 'Sentinel Forge',
    class: 'fighter',
    rarity: 'epic',
    level: 8,
    description: 'Interceptor robusto com defesa reforçada para combate prolongado.',
    lore: 'A Iron Sentinel tornou-se base de defesa de várias colônias periféricas.',
    price: 7600,
    stats: { speed: 88, hyperdrive: 64, storage: 40, fuel: 60, energy: 80, shield: 87 },
    unlocked: true,
    owned: false,
    placeholder_color: '#C0C0C0',
  },
  {
    id: 'celestial-ark',
    name: 'Celestial Ark',
    manufacturer: 'Arcadia Shipping',
    class: 'cargo',
    rarity: 'rare',
    level: 6,
    description: 'Transportadora de grande porte para rotas de colonização e suprimentos.',
    lore: 'A Celestial Ark conecta colônias distantes com uma capacidade de carga excepcional.',
    price: 5900,
    stats: { speed: 56, hyperdrive: 77, storage: 96, fuel: 69, energy: 70, shield: 72 },
    unlocked: true,
    owned: false,
    placeholder_color: '#4169E1',
  },
  {
    id: 'eclipse-runner',
    name: 'Eclipse Runner',
    manufacturer: 'Velour Labs',
    class: 'stealth',
    rarity: 'legendary',
    level: 10,
    description: 'Nave de elite para operações clandestinas de alta prioridade.',
    lore: 'A Eclipse Runner é uma lenda entre pilotos clandestinos, famosa por sua velocidade e sigilo.',
    price: 11200,
    stats: { speed: 95, hyperdrive: 92, storage: 31, fuel: 57, energy: 91, shield: 81 },
    unlocked: false,
    owned: false,
    placeholder_color: '#FF1493',
  },
  {
    id: 'galactic-sovereign',
    name: 'Galactic Sovereign',
    manufacturer: 'Imperial Ascendant',
    class: 'capital',
    rarity: 'legendary',
    level: 12,
    description: 'A maior nave capital da era atual, com capacidade tática e logística extraordinária.',
    lore: 'A Galactic Sovereign representa o auge da engenharia bélica, projetada para comandar frotas.',
    price: 14800,
    stats: { speed: 64, hyperdrive: 62, storage: 98, fuel: 66, energy: 90, shield: 98 },
    unlocked: false,
    owned: false,
    placeholder_color: '#FFD700',
  },
]
